### ISSUE TITLE
Running tests locally

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/tutorials#22]
I don't appear to be able to run the tests locally using the unix script (or the python script come to that, as the error below indicates). The shell script throws:

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "./run_notebook.py", line 14, in <module>
  File "./run_notebook.py", line 14, in <module>
    from scripting.unix import system, check_output
    from scripting.unix import system, check_output
ImportError: ImportErrorNo module named scripting.unix: 
No module named scripting.unix
```
I tried `conda install scripting`, but it claimed such a package doesn't exist.

What's up here? I should note I'm running zsh, not bash, if that's relevant.

**Comment by mcflugen** [comment]
Oops. Sorry. You need to install the `scripting` package. Try,
```bash
$ conda install scripting -c csdms-stack
```
and then try running `run_notebook.py`.
